from sqlalchemy import Column, Integer, Float, String, DateTime, LargeBinary, Boolean, TIMESTAMP
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func
from sqlalchemy.schema import FetchedValue
from datetime import datetime

Base = declarative_base()

class InvoicesSentToDatafile(Base):
    __tablename__ = 'tblInvoicesSentToDatafile'
    
    ID = Column(Integer, primary_key=True)
    InvMasNum = Column(String, nullable=False)
    
class InvoicesPaidTransactionsFromDatafile(Base):
    __tablename__ = 'tblInvoicesPaidTransactionsFromDatafile'
    
    ID = Column(Integer, primary_key=True)
    _ID = Column(Integer, nullable=False) # This is the transaction ID from Datafile table
    
class Currencies(Base):
    __tablename__ = 'tblCurrencies'
    
    CurrencyCode = Column(String, primary_key=True)
    CurrencySymbol = Column(String, nullable=True)
    CurrencyName = Column(String, nullable=True)
    CurrencyRate = Column(Float, nullable=True)
    SystemCurrency = Column(Boolean, nullable=True)
    
class Payments(Base):
    __tablename__ = 'tblPayments'
    
    ID = Column(Integer, primary_key=True)
    SONum = Column(String, nullable=True)
    

class SOInvDetail(Base):
    __tablename__ = 'tblSOInvDetail'
    
    InvDetNum = Column(String, primary_key=True)
    InvDetSONum = Column(String, primary_key=True)
    InvDetSOLineNum = Column(Integer, primary_key=True)
    InvDetSOLineType = Column(String, nullable=True)
    InvDetPartNo = Column(String, nullable=True)
    InvDetWH = Column(String, nullable=True)
    InvDetDes = Column(String, nullable=True)
    InvDetSOLineQty = Column(Float, nullable=True)
    InvDetSOLineSalPrice = Column(Float, nullable=True)
    InvDetSOLineTaxCode = Column(String, nullable=True)
    InvDetSOLineTaxRate = Column(Float, nullable=True)
    InvDetSOLineTax = Column(Float, nullable=True)
    InvDetSOLineDis = Column(Float, nullable=True)
    InvDetInvNum = Column(Integer, nullable=True)
    InvDetDateTime = Column(DateTime, nullable=True)
    InvDetUser = Column(String, nullable=True)
    InvDetSelect = Column(Boolean, nullable=False)
    upsize_ts = Column(TIMESTAMP, nullable=True)
    PCInvoiced = Column(Float, nullable=True)
    InvDetCZKVal = Column(String, nullable=True)
    InvDetCZKVAT = Column(String, nullable=True)
    
class SOInvMaster(Base):
    __tablename__ = 'tblSOInvMaster'
    
    InvMasNum = Column(String, primary_key=True)
    InvMasSONum = Column(String, nullable=True)
    InvMasDate = Column(DateTime, nullable=True)
    InvMasterTot = Column(Float, nullable=True)
    InvCarrier = Column(String, nullable=True)
    InvMasterPost = Column(Float, nullable=True)
    InvMasterPostTax = Column(Float, nullable=True)
    InvMasterTax = Column(Float, nullable=True)
    InvMasFootNotes = Column(String, nullable=True)
    InvMasLockedBy = Column(String, nullable=True)
    InvMasDataTime = Column(DateTime, nullable=True)
    InvMasLastPayType = Column(String, nullable=True)
    InvMasTotalPayed = Column(Float, nullable=True)
    InvMasUser = Column(String, nullable=True)
    InvMasDeleted = Column(DateTime, nullable=True)
    InvMasDispNoteNum = Column(String, nullable=True)
    upsize_ts = Column(TIMESTAMP, nullable=True)
    InvExportDate = Column(DateTime, nullable=True)
    InvMasDueDate = Column(DateTime, nullable=True)
    AcctExportDate = Column(DateTime, nullable=True)
    AcctExportStatus = Column(Integer, nullable=True)
    QBTxnId = Column(String, nullable=True)
    QBAcctExportStatus = Column(Integer, nullable=True)
    QBAcctExportDate = Column(DateTime, nullable=True)
    SetDisTaken = Column(Boolean, nullable=True)    
    SetDisVal = Column(Float, nullable=True)
    InvMasNumRef = Column(String, nullable=True)
    QBType = Column(String, nullable=True)
    InvExRate = Column(Float, nullable=True)
    InvCurrCodeCust = Column(String, nullable=True)
    QBAcctJornalExportStatus = Column(Integer, nullable=True)
    QBJournalTxnId = Column(String, nullable=True)
    Emailed = Column(Boolean, nullable=True) 
    DateEmailed = Column(DateTime, nullable=True)
    ProForma = Column(Integer, nullable=True)
    InvApprove = Column(Integer, nullable=True)
    
class SoMaster(Base):
    __tablename__ = 'tblSoMaster'

    SONum = Column(String, primary_key=True)
    SOQuoteNum = Column(String, nullable=True)
    SODefWH = Column(String, nullable=True)
    SOCustID = Column(Integer, nullable=True)
    SOCustRef = Column(String, nullable=True)
    SODes = Column(String, nullable=True)
    SOContactID_old = Column(Integer, nullable=True)
    SOStatus = Column(String, nullable=True)
    SONextLineNum = Column(Integer, nullable=True)
    SODateRaised = Column(DateTime, nullable=True)
    SOCarrier = Column(String, nullable=True)
    SOTotalCost = Column(Float, nullable=True)
    SOSalesMargin = Column(Float, nullable=True)
    SOTotalSalesValue = Column(Float, nullable=True)
    SOTotalSalesPost = Column(Float, nullable=True)
    SOTotalSalesPostTax = Column(Float, nullable=True)
    SOTotalSalesTax = Column(Float, nullable=True)
    SOTotalSalesPayed = Column(Float, nullable=True)
    SOShipToID = Column(Integer, nullable=True)
    SOOriginator = Column(String, nullable=True)
    SODeliveryLT = Column(String, nullable=True)
    SODueDate = Column(DateTime, nullable=True)
    SOValidity = Column(Integer, nullable=True)
    SOWarranty = Column(String, nullable=True)
    SOPaymentsLast = Column(String, nullable=True)
    SOPaymentsTotal = Column(Float, nullable=True)
    SOTerms = Column(String, nullable=True)
    SOHeadNotes = Column(String, nullable=True)
    SOFootNotes = Column(String, nullable=True)
    SOLockedBy = Column(String, nullable=True)
    upsize_ts = Column(TIMESTAMP, nullable=True)
    SOCurrCodeSys = Column(String, nullable=True)
    SOCurrCodeCust = Column(String, nullable=True)
    SOExRate = Column(Float, nullable=True)
    SOOriginatorNew = Column(String, nullable=True)
    SalesProgRptReady = Column(Boolean, nullable=True)
    SODelContact = Column(String, nullable=True)
    SOExportDate = Column(DateTime, nullable=True)
    Owner = Column(String, nullable=True)
    Machine = Column(String, nullable=True)
    AcctExportDate = Column(DateTime, nullable=True)
    SOAddContact1 = Column(String, nullable=True)
    SOAddContact2 = Column(String, nullable=True)
    SOAddContact3 = Column(String, nullable=True)
    QBAcctExportDate = Column(DateTime, nullable=True)
    QBAcctExportStatus = Column(Integer, nullable=True)
    QBTxnId = Column(String, nullable=True)
    SONote = Column(String, nullable=True)
    LastSupplementaryPricingDate = Column(DateTime, nullable=True)
    soInvName = Column(String, nullable=True)
    soInvAdd1 = Column(String, nullable=True)
    soInvAdd2 = Column(String, nullable=True)
    soInvAdd3 = Column(String, nullable=True)
    soInvAdd4 = Column(String, nullable=True)
    soInvAdd5 = Column(String, nullable=True)
    soInvPC = Column(String, nullable=True)
    soInvCountry = Column(String, nullable=True)
    soDelName = Column(String, nullable=True)
    soDelAdd1 = Column(String, nullable=True)
    soDelAdd2 = Column(String, nullable=True)
    soDelAdd3 = Column(String, nullable=True)
    soDelAdd4 = Column(String, nullable=True)
    soDelAdd5 = Column(String, nullable=True)
    soDelPC = Column(String, nullable=True)
    soDelCountry = Column(String, nullable=True)
    soContFirstName = Column(String, nullable=True)
    soContLastName = Column(String, nullable=True)
    soContEmail = Column(String, nullable=True)
    soContTel1 = Column(String, nullable=True)
    soContTel2 = Column(String, nullable=True)
    soWebOrderStatus = Column(String, nullable=True)
    soInvEmail = Column(String, nullable=True)
    SagePay_SecurityKey = Column(String, nullable=True)
    SagePay_VPSTxId = Column(String, nullable=True)
    SagePay_Status = Column(String, nullable=True)
    SagePay_TxAuthNo = Column(Integer, nullable=True)
    SagePay_Message = Column(String, nullable=True)
    SagePay_AVSCV2 = Column(String, nullable=True)
    SagePay_AddressResult = Column(String, nullable=True)
    SagePay_PostCodeResult = Column(String, nullable=True)
    SagePay_CV2Result = Column(String, nullable=True)
    SagePay_3DSecureStatus = Column(String, nullable=True)
    SagePay_CAVV = Column(String, nullable=True)
    SagePay_AddressStatus = Column(String, nullable=True)
    SagePay_PayerStatus = Column(String, nullable=True)
    SagePay_CardType = Column(String, nullable=True)
    SagePay_Last4Digits = Column(String, nullable=True)
    soPaymentStatus = Column(String, nullable=True)
    soPaymentType = Column(String, nullable=True)
    soWebID = Column(String, nullable=True)
    soInvTel = Column(String, nullable=True)
    soInvHeard = Column(String, nullable=True)
    soInvHeardOther = Column(String, nullable=True)
    SagePay_Reference = Column(String, nullable=True)
    soType = Column(String, nullable=True)
    SOUserDef1 = Column(String, nullable=True)
    SOUserDef2 = Column(String, nullable=True)
    SOUserDef3 = Column(String, nullable=True)
    SOUserDef4 = Column(String, nullable=True)
    SOUserDef5 = Column(String, nullable=True)
    SOUserDef6 = Column(String, nullable=True)
    LastLeadTimeFlag = Column(String, nullable=True)
    UserDefinedFields = Column(String, nullable=True)
    soINCOTERMS = Column(String, nullable=True)
    LeadTimeTransitType = Column(Integer, nullable=True)
    LeadTimeOrderType = Column(Integer, nullable=True)
    SOUserDef7 = Column(String, nullable=True)
    SOUserDef8 = Column(String, nullable=True)
    SOOrderType = Column(String, nullable=True)
    ProcessOrderLastStatusText = Column(String, nullable=True)
    ProcessOrderCompleteDate = Column(DateTime, nullable=True)
    DisPC_Order = Column(Float, nullable=True)
    SODueDateOriginal = Column(DateTime, nullable=True)
    ExportCount = Column(Integer, nullable=True)
    SOUserDef9 = Column(String, nullable=True)
    SOUserDef10 = Column(String, nullable=True)
    BatchID = Column(Integer, nullable=True)
    HoldDispatch = Column(Boolean, nullable=True)
    ProjectNumber = Column(String, nullable=True)
    SOUserDef11 = Column(String, nullable=True)
    SOUserDef12 = Column(String, nullable=True)
    SOContactID = Column(String, nullable=False)
    MultiOrdStatus = Column(String, nullable=True)
    DueDateCheckSO = Column(Integer, nullable=True)
    DisVal_Order = Column(Float, nullable=True)
    SOMasterType = Column(Integer, nullable=True)
    OmitFromAutoAlloc = Column(Integer, nullable=True)
        
class CCCust(Base):
    __tablename__ = 'tblCCCust'

    ID = Column (Integer, primary_key=True)
    CustAcctNo = Column(String, nullable=True)
    CustName = Column(String, nullable=True)
    AddLine1 = Column(String, nullable=True)
    AddLine2 = Column(String, nullable=True)
    Town = Column(String, nullable=True)
    City = Column(String, nullable=True)
    Address = Column(String, nullable=True)
    PostCode = Column(String, nullable=True)
    Region = Column(String, nullable=True)
    Country = Column(String, nullable=True)
    Tel = Column(String, nullable=True)
    Fax = Column(String, nullable=True)
    Email = Column(String, nullable=True)
    WebAddress = Column(String, nullable=True)
    CustType = Column(String, nullable=True)
    PriceAdj = Column(Float, nullable=True)
    Discount1 = Column(Float, nullable=True)
    Discount2 = Column(Float, nullable=True)
    Discount3 = Column(Float, nullable=True)
    Discount4 = Column(Float, nullable=True)
    CustPriceCode = Column(String, nullable=True)
    TypeOfInvTerms = Column(String, nullable=True)
    ShowImagesOnDocs = Column(Boolean, nullable=False)
    ActiveAcctFilter = Column(Boolean, nullable=False)
    LastContactView_old = Column(Integer, nullable=True)
    DefaultDelAddID = Column(Integer, nullable=True)
    DelAddressName = Column(String, nullable=True)
    DelAddressLine1 = Column(String, nullable=True)
    DelAddressLine2 = Column(String, nullable=True)
    DelAddressLine3 = Column(String, nullable=True)
    DelAddressLine4 = Column(String, nullable=True)
    DelPostCode = Column(String, nullable=True)
    TerritoryManCode = Column(Integer, nullable=True)
    TerritorySalesCode = Column(String, nullable=True)
    ArLastOrdVal = Column(Float, nullable=True)
    ArLastOrdDate = Column(DateTime, nullable=True)
    ArSpendNetToDate = Column(Float, nullable=True)
    ArSpendGrsToDate = Column(Float, nullable=True)
    ArPayedToDate = Column(Float, nullable=True)
    ArCreditLimit = Column(Float, nullable=True)
    ArCurBal = Column(Float, nullable=True)
    ArCurBal30days = Column(Float, nullable=True)
    ArCurBal60days = Column(Float, nullable=True)
    ArCurBal90days = Column(Float, nullable=True)
    ArCurBalCred = Column(Float, nullable=True)
    ArCurBalCred30days = Column(Float, nullable=True)
    ArCurBalCred60days = Column(Float, nullable=True)
    ArCurBalCred90days = Column(Float, nullable=True)
    ArIntNotepad = Column(String, nullable=True)
    UD1 = Column(String, nullable=True)
    UD2 = Column(String, nullable=True)
    UD3 = Column(String, nullable=True)
    UD4 = Column(String, nullable=True)
    UD5 = Column(String, nullable=True)
    UD6 = Column(String, nullable=True)
    UD7 = Column(String, nullable=True)
    UD8 = Column(String, nullable=True)
    UD9 = Column(String, nullable=True)
    UD10 = Column(String, nullable=True)
    UD11 = Column(String, nullable=True)
    UD12 = Column(String, nullable=True)
    UD13 = Column(String, nullable=True)
    UD14 = Column(String, nullable=True)
    UD15 = Column(String, nullable=True)
    UserDef = Column(String, nullable=True)
    DefTaxCode = Column(String, nullable=True)
    CustCurrCode = Column(String, nullable=True)
    CustEDIRef = Column(String, nullable=True)
    CustPayLedgerID = Column(String, nullable=True)
    WebCustUsername = Column(String, nullable=True)
    WebCustPassword = Column(String, nullable=True)
    CustTermsType = Column(Integer, nullable=True)
    CustTermsType1Days = Column(Integer, nullable=True)
    CustTermsType2Mths = Column(Integer, nullable=True)
    CustTermsType3Mths = Column(Integer, nullable=True)
    CustTermsType3Days = Column(Integer, nullable=True)
    CustLedgerID = Column(String, nullable=True)
    CustTAXNum = Column(String, nullable=True)
    QBAcctExportStatus = Column(Integer, nullable=True)
    QBAcctExportDate = Column(DateTime, nullable=True)
    QBListId = Column(String, nullable=True)
    SetDisActive = Column(Boolean, nullable=True)
    CustOnStop = Column(Boolean, nullable=True)
    LastUpdate = Column(DateTime, nullable=True)
    DocDelNoteID = Column(Integer, nullable=True)
    DocDelNoteHd = Column(String, nullable=True)
    DocDelNotepfx = Column(String, nullable=True)
    DocQuoteID = Column(Integer, nullable=True)
    DocPurchOrdID = Column(Integer, nullable=True)
    DocInvID = Column(Integer, nullable=True)
    LastContactView = Column(String, nullable=True)
    Guid_Id = Column(String, nullable=False)
    DocQuoteHd = Column(String, nullable=True)
    DocPurchOrdHd = Column(String, nullable=True)
    DocInvHd = Column(String, nullable=True)
    DocPickListID = Column(Integer, nullable=True)
    DocPickListHd = Column(String, nullable=True)
    EORINumber = Column(String, nullable=True)
    
class CYCSLA(Base):
    __tablename__ = 'CYC-SLA'
    
    _ID = Column(Integer, primary_key=True)
    ACCOUNT = Column(String, nullable=False)
    NAME = Column(String, nullable=True)
    COUNTRY = Column(String, nullable=True)
    BALANCE = Column(Float, nullable=True)
    FIRST_TX = Column(String, nullable=True)
    LAST_TX = Column(String, nullable=True)
    TAX = Column(String, nullable=True)
    DAYS_CR = Column(String, nullable=True)
    CR_LIMIT = Column(Float, nullable=True)
    STOP = Column(String, nullable=True)
    LAST_PAY_DATE = Column(DateTime, nullable=True)
    LAST_INV_DATE = Column(DateTime, nullable=True)
    SETUP_DATE = Column(DateTime, nullable=True)
    STATMNT_DATE = Column(DateTime, nullable=True)
    STATMNT_PAGE = Column(Integer, nullable=True)
    BAL_BF_YEAR = Column(Float, nullable=True)
    FIRST_ACTIVE = Column(String, nullable=True)
    
class QIPM(Base):
    __tablename__ = 'tblQIPM'

    PMPartID = Column(Integer, nullable=False)
    PMPartNo = Column(String, primary_key=True)
    PMWarehouse = Column(String, primary_key=True)
    PMItemType = Column(Integer, nullable=True)
    PMProdGrp = Column(String, nullable=True)
    PMDes = Column(String, nullable=True)
    PMQSortRef = Column(String, nullable=True)
    PMQHead = Column(String, nullable=True)
    PMQDes1 = Column(String, nullable=True)
    PMQDes2 = Column(String, nullable=True)
    PMDesExtend = Column(String, nullable=True)
    PMDesExtendUse = Column(Boolean, nullable=False)
    PMCostPrice = Column(Float, nullable=True)
    PMBOMCostPrice = Column(Float, nullable=True)
    PMSellMargin = Column(Float, nullable=True)
    PMSellMarginVal = Column(Float, nullable=True)
    PMSellPrice = Column(Float, nullable=True)
    PMTaxRate = Column(String, nullable=True)
    PMSellPriceIncTax = Column(Float, nullable=True)
    PMSellPriceDisSec = Column(String, nullable=True)
    PMLedgerID = Column(String, nullable=True)
    PMUOM = Column(String, nullable=True)
    PMUOMStk = Column(String, nullable=True)
    PMUOMSales = Column(String, nullable=True)
    PMStkItem = Column(Boolean, nullable=False)
    PMOnHandQty = Column(Float, nullable=True)
    PMOnOrder = Column(Float, nullable=True)
    PMAllocInsp = Column(Float, nullable=True)
    PMAllocSales = Column(Float, nullable=True)
    PMwip = Column(Float, nullable=True)
    PMMax = Column(Float, nullable=True)
    PMSafe = Column(Float, nullable=True)
    PMMin = Column(Float, nullable=True)
    PMEBQ = Column(Float, nullable=True)
    PMDefLoc = Column(String, nullable=True)
    PMDefSup = Column(String, nullable=True)
    InspReq = Column(Boolean, nullable=False)
    PMShowOnDocs = Column(Boolean, nullable=False)
    PMBarCode = Column(String, nullable=True)
    PMDrwNum = Column(String, nullable=True)
    PMDrwNumRev = Column(String, nullable=True)
    PMActive = Column(Boolean, nullable=False)
    PMNotePad = Column(String, nullable=True)
    PMDeleted = Column(Boolean, nullable=False)
    PMInfoPart = Column(Boolean, nullable=False)
    PopUpMsgSales = Column(String, nullable=True)
    PopUpMsgSalesUse = Column(Boolean, nullable=False)
    PMUserDef1Data = Column(String, nullable=True)
    PMUserDef2Data = Column(String, nullable=True)
    PMUserDef3Data = Column(String, nullable=True)
    PMUserDef4Data = Column(String, nullable=True)
    PMUserDef5Data = Column(String, nullable=True)
    PMUserDef6Data = Column(String, nullable=True)
    PMUserDef = Column(String, nullable=True)
    oppTotalTimeUOM = Column(String, nullable=True)
    oppPC = Column(Float, nullable=True)
    MatCert = Column(Boolean, nullable=True)
    RoutingCost = Column(Float, nullable=True)
    ExternalMnf = Column(Boolean, nullable=True)
    PMIntraStatCode = Column(String, nullable=True)
    PMIntraStatCodeDesc = Column(String, nullable=True)
    PMIntraStatKg = Column(Float, nullable=True)
    QIPMConvPurEA = Column(Float, nullable=True)
    QIPMConvPurOF = Column(Float, nullable=True)
    QIPMConvSopEA = Column(Float, nullable=True)
    QIPMConvSopOF = Column(Float, nullable=True)
    qipmPurchCat = Column(String, nullable=True)
    SoldByWght = Column(Boolean, nullable=True)
    PriceMatrixLink = Column(Boolean, nullable=True)
    PMWebImagePath1 = Column(String, nullable=True)
    WebImageLastUploadInfo = Column(String, nullable=True)
    WebPromotionalMain = Column(Boolean, nullable=True)
    WebPromotionalOther = Column(Boolean, nullable=True)
    PMProdGrpSub = Column(String, nullable=True)
    Owner = Column(String, nullable=True)
    Machine = Column(String, nullable=True)
    PMMakeToOrder = Column(Boolean, nullable=True)
    PMWipWo = Column(Float, nullable=True)
    PMFreeIssue = Column(Boolean, nullable=True)
    intCounter = Column(Integer, nullable=True)
    intCounterLabel = Column(String, nullable=True)
    POCallOff = Column(Boolean, nullable=True)
    PMLedgerIDPur = Column(String, nullable=True)
    timestamp = Column(TIMESTAMP, nullable=False)
    PMTopList = Column(Boolean, nullable=True)
    PMFeatured = Column(Boolean, nullable=True)
    PMClearance = Column(Boolean, nullable=True)
    PMNew = Column(Boolean, nullable=True)
    PMProdCode = Column(Integer, nullable=True)
    PMImage = Column(String, nullable=True)
    PMPartRef1 = Column(String, nullable=True)
    PMSpare = Column(String, nullable=True)
    PMContents = Column(String, nullable=True)
    PMSpec = Column(String, nullable=True)
    PMStandards = Column(String, nullable=True)
    PMComments = Column(String, nullable=True)
    PMTradeMark = Column(String, nullable=True)
    DiscCode = Column(String, nullable=True)
    DealerCode = Column(String, nullable=True)
    DealerCodeDesc = Column(String, nullable=True)
    SupplimentaryGrpID = Column(String, nullable=True)
    SupplimentaryGrpInvID = Column(String, nullable=True)
    SearchIndex = Column(String, nullable=True)
    SearchKeyWords = Column(String, nullable=True)
    ForecastLookFwd = Column(Integer, nullable=True)
    BarcodeEAN = Column(Boolean, nullable=True)
    ProdSort = Column(Integer, nullable=True)
    MDS_ID = Column(Integer, nullable=True)
    LeadTimeFlag = Column(String, nullable=True)
    InventoryClass = Column(String, nullable=True)
    PMUserDef7Data = Column(String, nullable=True)
    PMUserDef8Data = Column(String, nullable=True)
    PMUserDef9Data = Column(String, nullable=True)
    PMUserDef10Data = Column(String, nullable=True)
    PMUserDef11Data = Column(String, nullable=True)
    PMUserDef12Data = Column(String, nullable=True)
    PMUseSerialNo = Column(Boolean, nullable=True)
    ProdSize = Column(String, nullable=True)
    ProdColour = Column(String, nullable=True)
    ProdModel = Column(String, nullable=True)
    PMDefCOGSNomLedg = Column(String, nullable=True)
    PMStandardPurchCost = Column(Float, nullable=True)
    ProdBrand = Column(String, nullable=True)
    ProdSeason = Column(String, nullable=True)
    LastUpdate = Column(DateTime, nullable=True)
    PMWebImagePath2 = Column(String, nullable=True)
    PMWebImagePath3 = Column(String, nullable=True)
    PMWebImagePath4 = Column(String, nullable=True)
    PMWebImagePath5 = Column(String, nullable=True)
    PMBarcode2 = Column(String, nullable=True)
    PMBarcode3 = Column(String, nullable=True)
    PMWebShowOnOrder = Column(Boolean, nullable=True)
    PMUserDef13Data = Column(String, nullable=True)
    PMUserDef14Data = Column(String, nullable=True)
    PMUserDef15Data = Column(String, nullable=True)
    PMUserDef16Data = Column(String, nullable=True)
    PMUserDef17Data = Column(String, nullable=True)
    PMUserDef18Data = Column(String, nullable=True)
    PMUserDef19Data = Column(String, nullable=True)
    PMUserDef20Data = Column(String, nullable=True)
    MultiSourced = Column(Boolean, nullable=True)
    Type3Purchase = Column(Integer, nullable=True)
    PMSerialNumReq = Column(Integer, nullable=True)
    PMQuoteDemand = Column(Float, nullable=True)
    WHGrouped = Column(String, nullable=True)
    InvMatTracability = Column(Integer, nullable=True)
    StockOwner = Column(Integer, nullable=True)
    
class CYCSLT(Base):
    __tablename__ = 'CYC-SLT'
    
    _ID = Column(Integer, primary_key=True)
    TYPE = Column(Integer, nullable=True)
    DATE = Column(DateTime, nullable=True)
    DATE_ALLOC = Column(DateTime, nullable=True)
    ACCOUNT = Column(String, nullable=True)
    REF = Column(String, nullable=True)
    DESCRIPTION = Column(String, nullable=True)
    TOTAL = Column(String, nullable=True)
    ALLOCATED = Column(String, nullable=True)
    
    

    
    
    
    
    